### ISSUE TITLE
New version tag for the updated Package.swift

### ISSUE THREAD

**Issue by ThomasCle** [Hejki/SassPublishPlugin#1]
I've tried to use your plugin with version 0.1.0, but I kept getting this error in Xcode:
> The package product 'Publish' requires minimum platform version 12.0 for the macOS platform, but this target supports 10.13

Then I realised that the 0.1.0 version is at your first commit. Since then you've updated the Package.swift definition on the `master` branch, which fixes this problem. So when I pointed the dependency to your `master` branch instead, the error disappeared in Xcode.

Would is be possible for you to create new version with the newest commit on `master`? 😅🚀

**Comment by ThomasCle** [comment]
@Hejki 🙏🏻 ⬆️

**Comment by Hejki** [comment]
Tag 0.1.1 was created.
